/**
 * ============================================================================
 * BRASILEIRÃO SÉRIE A 2026 | Dashboard Application
 * ============================================================================
 * Frontend application served via Flask (scripts/server.py).
 * Data is collected by Python scripts and saved as local JSON.
 *
 * Architecture:
 *   - Data provided by scripts/fetch_sofascore.py and fetch_transfermarkt.py
 *   - Standings calculated locally from the results
 *   - "Update data" button triggers the pipeline via SSE (Server-Sent Events)
 *   - Real-time progress bar during collection
 *   - Rendering via template strings injected into the DOM
 *   - Chart.js for interactive charts
 *
 * @author Dashboard Futebol Brasil
 * @version 3.0.0
 * ============================================================================
 */

/* --------------------------------------------------------------------------
 * CONFIGURATION CONSTANTS
 * -------------------------------------------------------------------------- */

/** Endpoints of the JSON data generated by the Python scripts */
const DATA_BRASILEIRAO = 'data/brasileirao.json';
const DATA_MARKET      = 'data/market-values.json';

/** Detects whether it runs on GitHub Pages (static) or localhost (Flask) */
const IS_STATIC = window.location.hostname !== 'localhost'
    && window.location.hostname !== '127.0.0.1';

/** EUR → BRL rate (overridden by the JSON when available) */
let EUR_TO_BRL = 6.20;


/* --------------------------------------------------------------------------
 * GLOBAL APPLICATION STATE
 * -------------------------------------------------------------------------- */

/**
 * Centralised dashboard state.
 * Every render function reads from this object.
 *
 * @type {{
 *   standings:     Array<TeamStats>|null,
 *   selectedTeam:  string,
 *   selectedRound: number|null,
 *   lastUpdated:   Date|null,
 *   allMatches:    Array<Object>,
 *   activeTab:     string,
 *   chartInstances: Array<Chart>
 * }}
 */
let appState = {
    standings:      null,
    selectedTeam:   'All teams',
    selectedRound:  null,
    lastUpdated:    null,
    allMatches:     [],
    activeTab:      'tabela',
    chartInstances: [],
    season:         null,
    mercadoSort:    'value',    // field to sort by: 'name','team','position','age','value'
    mercadoSortDir: 'desc',     // 'asc' or 'desc'
};


/* ============================================================================
 * SECTION 2: CALCULATIONS AND DATA PROCESSING
 * ============================================================================ */

/**
 * Calculates the full standings from match results.
 * Processes goals, points, wins/draws/losses (home and away),
 * and sorts by points → goal difference → goals scored.
 *
 * @param {Array<Object>} matches - Array of finished matches from the API
 * @returns {{
 *   standings:  Array<TeamStats>,
 *   teamBadges: Object<string, string>
 * }}
 */
function calculateStandings(matches) {
    const teams = {};
    const teamBadges = {};

    matches.forEach(match => {
        // Skip unplayed matches (null score = not played yet)
        if (match.intHomeScore === null || match.intHomeScore === undefined || match.intHomeScore === '') return;

        const home = match.strHomeTeam;
        const away = match.strAwayTeam;
        const homeScore = parseInt(match.intHomeScore) || 0;
        const awayScore = parseInt(match.intAwayScore) || 0;
        const matchDate = new Date(match.dateEvent + 'T12:00:00');

        // Initialise teams if they do not exist yet
        [home, away].forEach(t => {
            if (!teams[t]) {
                teams[t] = {
                    name: t, points: 0, played: 0,
                    wins: 0, draws: 0, losses: 0,
                    goalsFor: 0, goalsAgainst: 0,
                    homeWins: 0, homeDraws: 0, homeLosses: 0,
                    homeGoalsFor: 0, homeGoalsAgainst: 0,
                    awayWins: 0, awayDraws: 0, awayLosses: 0,
                    awayGoalsFor: 0, awayGoalsAgainst: 0,
                    lastMatchDate: null, matches: []
                };
            }
        });

        // Badges
        teamBadges[home] = match.strHomeTeamBadge;
        teamBadges[away] = match.strAwayTeamBadge;

        // Home team stats
        teams[home].played++;
        teams[home].goalsFor += homeScore;
        teams[home].goalsAgainst += awayScore;
        teams[home].homeGoalsFor += homeScore;
        teams[home].homeGoalsAgainst += awayScore;
        if (!teams[home].lastMatchDate || matchDate > teams[home].lastMatchDate) {
            teams[home].lastMatchDate = matchDate;
        }
        teams[home].matches.push({
            opponent: away, score: homeScore, conceded: awayScore,
            isHome: true, date: matchDate
        });

        // Away team stats
        teams[away].played++;
        teams[away].goalsFor += awayScore;
        teams[away].goalsAgainst += homeScore;
        teams[away].awayGoalsFor += awayScore;
        teams[away].awayGoalsAgainst += homeScore;
        if (!teams[away].lastMatchDate || matchDate > teams[away].lastMatchDate) {
            teams[away].lastMatchDate = matchDate;
        }
        teams[away].matches.push({
            opponent: home, score: awayScore, conceded: homeScore,
            isHome: false, date: matchDate
        });

        // Points distribution
        if (homeScore > awayScore) {
            teams[home].wins++; teams[home].points += 3; teams[home].homeWins++;
            teams[away].losses++; teams[away].awayLosses++;
        } else if (homeScore < awayScore) {
            teams[away].wins++; teams[away].points += 3; teams[away].awayWins++;
            teams[home].losses++; teams[home].homeLosses++;
        } else {
            teams[home].draws++; teams[home].points += 1; teams[home].homeDraws++;
            teams[away].draws++; teams[away].points += 1; teams[away].awayDraws++;
        }
    });

    // Sorting: points → goal difference → goals scored
    const standings = Object.values(teams).sort((a, b) => {
        if (b.points !== a.points) return b.points - a.points;
        const sgDiff = (b.goalsFor - b.goalsAgainst) - (a.goalsFor - a.goalsAgainst);
        if (sgDiff !== 0) return sgDiff;
        return b.goalsFor - a.goalsFor;
    });

    standings.forEach((team, i) => { team.position = i + 1; });
    return { standings, teamBadges };
}


function buildPointsProgression(matches) {
    const rounds = [...new Set(matches.map(m => parseInt(m.intRound)))].sort((a, b) => a - b);
    const teamNames = [...new Set(matches.flatMap(m => [m.strHomeTeam, m.strAwayTeam]))];
    const cumPts = {};
    teamNames.forEach(t => { cumPts[t] = 0; });
    const series = {};
    teamNames.forEach(t => { series[t] = []; });
    rounds.forEach(round => {
        matches.filter(m => parseInt(m.intRound) === round).forEach(m => {
            const hs = parseInt(m.intHomeScore) || 0;
            const as = parseInt(m.intAwayScore) || 0;
            if (hs > as) cumPts[m.strHomeTeam] += 3;
            else if (hs < as) cumPts[m.strAwayTeam] += 3;
            else { cumPts[m.strHomeTeam] += 1; cumPts[m.strAwayTeam] += 1; }
        });
        teamNames.forEach(t => { series[t].push(cumPts[t]); });
    });
    return { rounds, series };
}


/* ============================================================================
 * SECTION 3: FORMATTING
 * ============================================================================ */

/**
 * Formats a date as DD/MM/YYYY.
 * @param {Date|string} date
 * @returns {string}
 */
function formatDate(date) {
    if (!date) return '';
    const d = new Date(date);
    return `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}/${d.getFullYear()}`;
}

/**
 * Formats a short date DD/MM (no year).
 * @param {Date|string} date
 * @returns {string}
 */
function formatDateShort(date) {
    if (!date) return '';
    const d = new Date(date);
    return `${String(d.getDate()).padStart(2, '0')}/${String(d.getMonth() + 1).padStart(2, '0')}`;
}

/**
 * Formats the time as HH:MM.
 * @param {Date} date
 * @returns {string}
 */
function formatTime(date) {
    if (!date) return '';
    return date.toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
}

/**
 * Formats a market value in EUR for compact display.
 * E.g. 45000000 → "€ 45.0M", 500000 → "€ 500K"
 *
 * @param {number} v - Value in EUR
 * @returns {string}
 */
function formatMarketValue(v) {
    if (v >= 1000000) return `\u20AC ${(v / 1000000).toFixed(1)}M`;
    if (v >= 1000) return `\u20AC ${Math.round(v / 1000)}K`;
    return `\u20AC ${v}`;
}

function formatMarketValueBRL(v) {
    const brl = v * EUR_TO_BRL;
    if (brl >= 1000000) return `R$ ${(brl / 1000000).toFixed(1)}M`;
    if (brl >= 1000) return `R$ ${Math.round(brl / 1000)}K`;
    return `R$ ${Math.round(brl)}`;
}


/* ============================================================================
 * SECTION 4: RENDER FUNCTIONS
 * ============================================================================ */

/**
 * Renders the header with title, filters and timestamp.
 *
 * @param {number} latestRound - Latest available round
 * @param {string} selectedTeam - Team selected in the filter
 * @param {number} selectedRound - Selected round
 * @param {Date|null} lastUpdated - Date of the last update
 * @returns {string} Header HTML
 */
function renderHeader(latestRound, selectedTeam, selectedRound, lastUpdated) {
    const timestamp = lastUpdated
        ? `${formatDate(lastUpdated)} at ${formatTime(lastUpdated)}`
        : 'Waiting for data';

    return `
        <div class="header">
            <div class="header-content">
                <div class="header-title">
                    <h1>\u26BD Brasileirão Série A</h1>
                    <span class="subtitle">Season ${appState.season} • Interactive Dashboard</span>
                </div>
                <div class="header-controls">
                    <select class="select-team" id="teamFilter">
                        <option value="All teams">All teams</option>
                    </select>
                    <button class="theme-toggle" id="themeToggle" title="Toggle theme">${document.documentElement.getAttribute('data-theme') === 'light' ? '\u2600\uFE0F' : '\uD83C\uDF19'}</button>
                </div>
            </div>
            <div class="header-timestamp">Updated ${timestamp}</div>
        </div>
    `;
}

/**
 * Renders the league-wide KPI cards.
 * Always the same regardless of the selected team.
 */
function renderKPIs(standings, allMatches) {
    if (!standings || standings.length === 0) {
        return `<div class="kpi-grid kpi-empty-wrapper">
            <div class="kpi-empty">No data loaded. Data is updated automatically every day.</div>
        </div>`;
    }

    const kpi = (label, value, detail = '', color = '') =>
        `<div class="kpi-card">
            <div class="kpi-label">${label}</div>
            <div class="kpi-value small">${value}</div>
            ${detail ? `<div class="kpi-detail" style="color:${color || 'var(--text-secondary)'}">${detail}</div>` : ''}
        </div>`;

    const selectedTeam = appState.selectedTeam;

    // ── KPIs for the selected team ────────────────────────────────
    if (selectedTeam !== 'All teams') {
        const t = standings.find(s => s.name === selectedTeam);
        if (!t) return '';

        const maxPts = t.played * 3 || 1;
        const aprov = Math.round(t.points / maxPts * 100);
        const aprovColor = aprov >= 60 ? 'var(--accent-green)' : aprov >= 40 ? 'var(--accent-yellow)' : 'var(--accent-red)';
        const sg = t.goalsFor - t.goalsAgainst;
        const sgStr = sg > 0 ? `+${sg}` : String(sg);
        const sgColor = sg > 0 ? 'var(--accent-green)' : sg < 0 ? 'var(--accent-red)' : 'var(--text-secondary)';

        // Current streak
        const sorted = [...t.matches].sort((a, b) => new Date(b.date) - new Date(a.date));
        let streakType = '', streakCount = 0;
        for (const m of sorted) {
            const res = m.score > m.conceded ? 'W' : m.score === m.conceded ? 'D' : 'L';
            if (!streakType) { streakType = res; streakCount = 1; }
            else if (res === streakType) streakCount++;
            else break;
        }
        const streakLabel = streakCount > 0 ? `${streakCount}${streakType}` : '-';
        const streakColor = streakType === 'W' ? 'var(--accent-green)' : streakType === 'L' ? 'var(--accent-red)' : 'var(--accent-yellow)';

        const homePts = t.homeWins * 3 + t.homeDraws;
        const awayPts = t.awayWins * 3 + t.awayDraws;

        return `
            <div class="kpi-grid">
                ${kpi('Points', t.points, `${t.played} played • ${t.wins}W ${t.draws}D ${t.losses}L`)}
                ${kpi('Points %', `${aprov}%`, `${t.points} of ${t.played * 3} possible`, aprovColor)}
                ${kpi('Position', `${t.position}`, `of 20 teams`)}
                ${kpi('Current Streak', streakLabel, `latest results`, streakColor)}
            </div>
            <div class="kpi-grid" style="margin-top:0">
                ${kpi('Goals', `${t.goalsFor} / ${t.goalsAgainst}`, 'for / against')}
                ${kpi('Goal Difference', sgStr, `${t.goalsFor} GF • ${t.goalsAgainst} GA`, sgColor)}
                ${kpi('Home', `${homePts} pts`, `${t.homeWins}W ${t.homeDraws}D ${t.homeLosses}L`, 'var(--accent-blue)')}
                ${kpi('Away', `${awayPts} pts`, `${t.awayWins}W ${t.awayDraws}D ${t.awayLosses}L`, 'var(--accent-blue)')}
            </div>
        `;
    }

    // ── League-wide KPIs ─────────────────────────────────────
    const finished   = allMatches.filter(m => m.intHomeScore !== null && m.intHomeScore !== undefined && m.intHomeScore !== '').length;
    const totalGoals = allMatches.reduce((s, m) =>
        s + (parseInt(m.intHomeScore) || 0) + (parseInt(m.intAwayScore) || 0), 0);
    const avgGoals   = finished > 0 ? (totalGoals / finished).toFixed(2) : '0.0';

    const leader      = standings[0];
    const bestAttack  = standings.reduce((max, t) => t.goalsFor > max.goalsFor ? t : max);
    const bestDefense = standings.reduce((min, t) => t.goalsAgainst < min.goalsAgainst ? t : min);

    let bestStreak = { team: '', streak: 0 };
    standings.forEach(team => {
        const sorted = [...team.matches].sort((a, b) => new Date(b.date) - new Date(a.date));
        let streak = 0;
        for (const m of sorted) { if (m.score > m.conceded) streak++; else break; }
        if (streak > bestStreak.streak) bestStreak = { team: team.name, streak };
    });

    const topHomeTeam = standings.reduce((max, t) =>
        (t.homeWins * 3 + t.homeDraws) > (max.homeWins * 3 + max.homeDraws) ? t : max);
    const topAwayTeam = standings.reduce((max, t) =>
        (t.awayWins * 3 + t.awayDraws) > (max.awayWins * 3 + max.awayDraws) ? t : max);

    return `
        <div class="kpi-grid">
            ${kpi('Matches Played', finished, `${totalGoals} goals in total`)}
            ${kpi('Goals per Match', avgGoals, 'average')}
            ${kpi('Leader', leader.name, `${leader.points} pts • ${leader.played} P`)}
            ${kpi('Longest Win Streak', bestStreak.streak > 0 ? `${bestStreak.streak}W` : '-', bestStreak.team, 'var(--accent-green)')}
        </div>
        <div class="kpi-grid" style="margin-top:0">
            ${kpi('Best Attack', bestAttack.name, `${bestAttack.goalsFor} goals scored`, 'var(--accent-green)')}
            ${kpi('Best Defence', bestDefense.name, `${bestDefense.goalsAgainst} goals conceded`, 'var(--accent-green)')}
            ${kpi('Best Home Team', topHomeTeam.name, `${topHomeTeam.homeWins * 3 + topHomeTeam.homeDraws} pts at home`, 'var(--accent-blue)')}
            ${kpi('Best Away Team', topAwayTeam.name, `${topAwayTeam.awayWins * 3 + topAwayTeam.awayDraws} pts away`, 'var(--accent-blue)')}
        </div>
    `;
}

/**
 * Renders the standings table with coloured zones (no bullets).
 * Zones are shown only by the row's left border.
 *
 * @param {Array<TeamStats>} standings - Sorted standings
 * @param {Object} teamBadges - Badge map (unused, kept for compatibility)
 * @param {string} selectedTeam - Team selected for highlighting
 * @returns {string} Table HTML
 */
function renderStandings(standings, teamBadges, selectedTeam) {
    if (!standings || standings.length === 0) {
        return `<div class="standings-wrapper"><div class="standings-empty">No data available.</div></div>`;
    }

    let html = `<div class="standings-wrapper"><table class="standings-table"><thead><tr>
        <th>#</th><th></th><th>Team</th><th class="th-center">Pts</th><th class="th-center">P</th><th class="th-center hide-mobile">W</th><th class="th-center hide-mobile">D</th><th class="th-center hide-mobile">L</th><th class="th-center hide-mobile">GF</th><th class="th-center hide-mobile">GA</th><th class="th-center">GD</th><th class="th-center">Last 5</th><th class="th-center hide-mobile">Last</th>
    </tr></thead><tbody>`;

    standings.forEach(team => {
        // 2026 standings zone (CSS class only, for the left border)
        let zoneClass = '';
        if (team.position <= 4)       zoneClass = 'zone-libertadores';
        else if (team.position === 5) zoneClass = 'zone-pre-libertadores';
        else if (team.position <= 11) zoneClass = 'zone-sudamericana';
        else if (team.position >= 17) zoneClass = 'zone-rebaixamento';

        const highlighted = selectedTeam !== 'All teams' && team.name === selectedTeam
            ? 'highlighted' : '';

        // Last 5 matches (form dots)
        const last5 = [...team.matches]
            .sort((a, b) => new Date(b.date) - new Date(a.date))
            .slice(0, 5)
            .reverse();

        let formHtml = '<div class="form-dots">';
        last5.forEach(m => {
            if (m.score > m.conceded)      formHtml += '<div class="form-dot win" title="Win"></div>';
            else if (m.score === m.conceded) formHtml += '<div class="form-dot draw" title="Draw"></div>';
            else                            formHtml += '<div class="form-dot loss" title="Loss"></div>';
        });
        formHtml += '</div>';

        const gd = team.goalsFor - team.goalsAgainst;
        const gdClass = gd >= 0 ? 'positive' : 'negative';
        const lastDate = team.lastMatchDate ? formatDateShort(team.lastMatchDate) : '-';

        html += `<tr class="${zoneClass} ${highlighted}">
            <td class="position-cell">${team.position}</td>
            <td><img src="${team.badge || ''}" alt="${team.name}" class="team-logo" onerror="this.style.display='none'"></td>
            <td class="team-cell"><span class="team-name">${team.name}</span></td>
            <td class="points-cell">${team.points}</td>
            <td class="stat-cell">${team.played}</td>
            <td class="stat-cell hide-mobile">${team.wins}</td>
            <td class="stat-cell hide-mobile">${team.draws}</td>
            <td class="stat-cell hide-mobile">${team.losses}</td>
            <td class="stat-cell hide-mobile">${team.goalsFor}</td>
            <td class="stat-cell hide-mobile">${team.goalsAgainst}</td>
            <td class="goal-diff ${gdClass}">${gd > 0 ? '+' : ''}${gd}</td>
            <td class="stat-cell">${formHtml}</td>
            <td class="last-match-date hide-mobile">${lastDate}</td>
        </tr>`;
    });

    html += `</tbody></table>
        <div class="zone-legend">
            <div class="zone-legend-item"><div class="zone-legend-dot" style="background:var(--zone-lib)"></div><span>Libertadores (1–4)</span></div>
            <div class="zone-legend-item"><div class="zone-legend-dot" style="background:var(--zone-pre-lib)"></div><span>Libertadores qualifiers (5)</span></div>
            <div class="zone-legend-item"><div class="zone-legend-dot" style="background:var(--zone-sul)"></div><span>Sudamericana (6–11)</span></div>
            <div class="zone-legend-item"><div class="zone-legend-dot" style="background:var(--zone-rel)"></div><span>Relegation (17–20)</span></div>
        </div></div>`;
    return html;
}



function renderEstatisticasContent() {
    const standings = appState.standings || [];
    const team = appState.selectedTeam;
    const isAll = team === 'All teams';
    let html = '';

    if (isAll) {
        // ── League KPIs ──────────────────────────────────────────
        const playedMatches = appState.allMatches.filter(m =>
            m.intHomeScore !== null && m.intHomeScore !== undefined && m.intHomeScore !== ''
        );
        const totalGoals = playedMatches.reduce((s, m) =>
            s + (parseInt(m.intHomeScore)||0) + (parseInt(m.intAwayScore)||0), 0);
        const avgGoals = playedMatches.length > 0
            ? (totalGoals / playedMatches.length).toFixed(2) : '—';
        const homeWins = playedMatches.filter(m =>
            (parseInt(m.intHomeScore)||0) > (parseInt(m.intAwayScore)||0)).length;
        const homePct  = playedMatches.length > 0
            ? Math.round(homeWins / playedMatches.length * 100) : 0;
        const latestRound = standings.length > 0
            ? Math.max(...standings.map(t => t.played || 0)) : 0;
        const cleanSheets = playedMatches.filter(m =>
            (parseInt(m.intAwayScore)||0) === 0).length +
            playedMatches.filter(m => (parseInt(m.intHomeScore)||0) === 0).length;

        html += `<div class="kpi-grid" style="margin-bottom:24px">
            <div class="kpi-card">
                <div class="kpi-label">Current Round</div>
                <div class="kpi-value">${latestRound}</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Total Goals</div>
                <div class="kpi-value">${totalGoals}</div>
                <div class="kpi-detail">${avgGoals} per match</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Home Wins</div>
                <div class="kpi-value">${homePct}%</div>
                <div class="kpi-detail">${homeWins} of ${playedMatches.length} matches</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Clean Sheets</div>
                <div class="kpi-value">${cleanSheets}</div>
                <div class="kpi-detail">Goals conceded = 0</div>
            </div>
        </div>`;

        // ── Top scorers + assists ─────────────────────────────
        const playerStats = window.BRASILEIRAO_DATA?.player_stats || [];
        const scorers   = playerStats.filter(p => p.cat === 'goalsLeaders').sort((a,b) => b.goals - a.goals);
        const assisters = playerStats.filter(p => p.cat === 'assistsLeaders').sort((a,b) => b.assists - a.assists);

        const playerTable = (players, valueKey, valueLabel) => {
            if (!players.length) return '<div style="color:var(--text-muted);font-size:12px;padding:8px">No data available.</div>';
            return `<div class="market-table-wrapper"><table class="market-table">
                <thead><tr><th>#</th><th>Player</th><th class="th-center">P</th><th class="th-center">${valueLabel}</th></tr></thead>
                <tbody>${players.slice(0,15).map((p,i) => `<tr>
                    <td class="market-rank">${i+1}</td>
                    <td style="font-weight:500">${p.name}</td>
                    <td class="stat-cell">${p.matches}</td>
                    <td style="text-align:center;font-weight:700;color:var(--accent-green)">${p[valueKey]}</td>
                </tr>`).join('')}</tbody>
            </table></div>`;
        };

        html += `<div class="charts-grid" style="margin-bottom:24px">
            <div class="chart-wrapper"><h3 class="chart-title">⚽ Top Scorers</h3>${playerTable(scorers,'goals','Goals')}</div>
            <div class="chart-wrapper"><h3 class="chart-title">🎯 Assists</h3>${playerTable(assisters,'assists','Assist.')}</div>
        </div>`;

        // ── Best attack / best defence ─────────────────────────
        const topAttack  = [...standings].sort((a,b) => b.goalsFor - a.goalsFor).slice(0,8);
        const topDefense = [...standings].sort((a,b) => a.goalsAgainst - b.goalsAgainst).slice(0,8);

        const rankTable = (teams, col, label, colorFn) =>
            `<div class="market-table-wrapper"><table class="market-table">
                <thead><tr><th>#</th><th>Team</th><th class="th-center">P</th><th class="th-center">${label}</th></tr></thead>
                <tbody>${teams.map((t,i) => `<tr>
                    <td class="market-rank">${i+1}</td>
                    <td style="font-weight:500">${t.name}</td>
                    <td class="stat-cell">${t.played}</td>
                    <td style="text-align:center;font-weight:700;color:${colorFn(t)}">${t[col]}</td>
                </tr>`).join('')}</tbody>
            </table></div>`;

        html += `<div class="charts-grid" style="margin-bottom:24px">
            <div class="chart-wrapper">
                <h3 class="chart-title">🔥 Best Attack</h3>
                ${rankTable(topAttack,'goalsFor','GP', t => 'var(--accent-green)')}
            </div>
            <div class="chart-wrapper">
                <h3 class="chart-title">🛡️ Best Defence</h3>
                ${rankTable(topDefense,'goalsAgainst','GC', t => t.goalsAgainst <= 5 ? 'var(--accent-green)' : t.goalsAgainst <= 10 ? 'var(--accent-yellow)' : 'var(--accent-red)')}
            </div>
        </div>`;

    } else {
        // ── Selected team view ──────────────────
        const t = standings.find(s => s.name === team);
        if (!t) return `<div class="historico-empty">Team "${team}" not found in the data.</div>`;

        const maxPts   = t.played * 3 || 1;
        const aprov    = Math.round(t.points / maxPts * 100);
        const sg       = t.goalsFor - t.goalsAgainst;
        const sgStr    = sg > 0 ? `+${sg}` : String(sg);
        const sgColor  = sg > 0 ? 'var(--accent-green)' : sg < 0 ? 'var(--accent-red)' : 'var(--text-secondary)';
        const aprovColor = aprov >= 60 ? 'var(--accent-green)' : aprov >= 40 ? 'var(--accent-yellow)' : 'var(--accent-red)';

        // Form dots
        const last5 = [...(t.matches||[])].sort((a,b) => new Date(b.date)-new Date(a.date)).slice(0,5).reverse();
        const formDots = last5.map(m => {
            const r = m.score > m.conceded ? 'win' : m.score === m.conceded ? 'draw' : 'loss';
            return `<div class="form-dot ${r}" title="${m.opponent}"></div>`;
        }).join('');

        html += `<div class="kpi-grid" style="margin-bottom:24px">
            <div class="kpi-card">
                <div class="kpi-label">Points</div>
                <div class="kpi-value">${t.points}</div>
                <div class="kpi-detail">${t.played} played</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Points %</div>
                <div class="kpi-value" style="color:${aprovColor}">${aprov}%</div>
                <div class="kpi-detail">${t.wins}W ${t.draws}D ${t.losses}L</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Goals</div>
                <div class="kpi-value">${t.goalsFor}<span style="font-size:14px;color:var(--text-muted)"> / ${t.goalsAgainst}</span></div>
                <div class="kpi-detail">For / Against</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Goal Difference</div>
                <div class="kpi-value" style="color:${sgColor}">${sgStr}</div>
                <div class="kpi-detail">Position: ${t.position}</div>
            </div>
        </div>`;

        // Recent form
        html += `<div class="charts-grid" style="margin-bottom:24px">
            <div class="chart-wrapper">
                <h3 class="chart-title">Recent Form | Last 5</h3>
                <div style="display:flex;gap:8px;margin-bottom:16px">${formDots}</div>
                <div class="market-table-wrapper"><table class="market-table">
                    <thead><tr><th>Opponent</th><th class="th-center">Score</th><th class="th-center">Result</th></tr></thead>
                    <tbody>${last5.map(m => {
                        const res = m.score > m.conceded ? 'W' : m.score === m.conceded ? 'D' : 'L';
                        const col = m.score > m.conceded ? 'var(--accent-green)' : m.score === m.conceded ? 'var(--accent-yellow)' : 'var(--accent-red)';
                        const where = m.isHome ? '🏠' : '✈️';
                        return `<tr>
                            <td>${where} ${m.opponent}</td>
                            <td class="stat-cell">${m.score} × ${m.conceded}</td>
                            <td style="text-align:center;font-weight:700;color:${col}">${res}</td>
                        </tr>`;
                    }).join('')}
                    </tbody></table></div>
            </div>
            <div class="chart-wrapper">
                <h3 class="chart-title">Home vs Away</h3>
                <div class="market-table-wrapper"><table class="market-table">
                    <thead><tr><th>Venue</th><th class="th-center">P</th><th class="th-center">W</th><th class="th-center">D</th><th class="th-center">L</th><th class="th-center">GF</th><th class="th-center">GA</th><th class="th-center">Pts</th></tr></thead>
                    <tbody>
                        <tr>
                            <td style="font-weight:600">🏠 Home</td>
                            <td class="stat-cell">${t.homeWins+t.homeDraws+t.homeLosses}</td>
                            <td class="stat-cell">${t.homeWins}</td>
                            <td class="stat-cell">${t.homeDraws}</td>
                            <td class="stat-cell">${t.homeLosses}</td>
                            <td class="stat-cell">${t.homeGoalsFor}</td>
                            <td class="stat-cell">${t.homeGoalsAgainst}</td>
                            <td class="points-cell">${t.homeWins*3+t.homeDraws}</td>
                        </tr>
                        <tr>
                            <td style="font-weight:600">✈️ Away</td>
                            <td class="stat-cell">${t.awayWins+t.awayDraws+t.awayLosses}</td>
                            <td class="stat-cell">${t.awayWins}</td>
                            <td class="stat-cell">${t.awayDraws}</td>
                            <td class="stat-cell">${t.awayLosses}</td>
                            <td class="stat-cell">${t.awayGoalsFor}</td>
                            <td class="stat-cell">${t.awayGoalsAgainst}</td>
                            <td class="points-cell">${t.awayWins*3+t.awayDraws}</td>
                        </tr>
                    </tbody></table></div>
            </div>
        </div>`;
    }

    return html;
}

/**
 * Renders the standings charts (goals and points %).
 * Returns HTML and data for later Chart.js initialisation.
 *
 * @param {Array<TeamStats>} standings - Standings
 * @returns {{ html: string, goalsData: Object, performanceData: Object }}
 */
function renderCharts(standings) {
    const top10 = standings.slice(0, 10);

    const goalsData = {
        labels: top10.map(t => t.name),
        datasets: [
            { label: 'Gols Marcados', data: top10.map(t => t.goalsFor), backgroundColor: '#059669', borderRadius: 4 },
            { label: 'Gols Sofridos', data: top10.map(t => t.goalsAgainst), backgroundColor: '#dc2626', borderRadius: 4 }
        ]
    };

    const performanceData = {
        labels: standings.map(t => t.name),
        datasets: [{
            label: 'Points (%)',
            data: standings.map(t => {
                const p = t.played * 3;
                return p > 0 ? Math.round((t.points / p) * 100) : 0;
            }),
            backgroundColor: standings.map(t => {
                const p = t.played * 3;
                const perc = p > 0 ? (t.points / p) * 100 : 0;
                return perc >= 70 ? '#059669' : perc >= 50 ? '#d97706' : '#dc2626';
            }),
            borderRadius: 4
        }]
    };

    // Form table (last 5 for every team)
    let formTableHtml = `<div class="chart-wrapper" style="grid-column:1/-1">
        <h3 class="chart-title">Recent Form | Last 5 Matches</h3>
        <div class="form-table">
        <table class="standings-table"><thead><tr>
            <th>#</th><th>Team</th><th class="th-center">Pts</th><th class="th-center">P</th>
            <th class="th-center">Pts %</th><th class="th-center">Form</th>
        </tr></thead><tbody>`;
    standings.forEach(team => {
        const poss  = team.played > 0 ? Math.round(team.points / (team.played * 3) * 100) : 0;
        const color = poss >= 60 ? 'var(--accent-green)' : poss >= 40 ? 'var(--accent-yellow)' : 'var(--accent-red)';
        const last5 = [...team.matches]
            .sort((a, b) => new Date(b.date) - new Date(a.date))
            .slice(0, 5).reverse();
        const formDots = last5.map(m => {
            const res = m.score > m.conceded ? 'win' : m.score === m.conceded ? 'draw' : 'loss';
            return `<div class="form-dot ${res}"></div>`;
        }).join('');
        let zone = '';
        if (team.position <= 4)       zone = 'zone-libertadores';
        else if (team.position === 5) zone = 'zone-pre-libertadores';
        else if (team.position <= 11) zone = 'zone-sudamericana';
        else if (team.position >= 17) zone = 'zone-rebaixamento';
        formTableHtml += `<tr class="${zone}">
            <td class="position-cell">${team.position}</td>
            <td class="team-cell"><span class="team-name">${team.name}</span></td>
            <td class="points-cell">${team.points}</td>
            <td class="stat-cell">${team.played}</td>
            <td class="stat-cell" style="font-weight:700;color:${color}">${poss}%</td>
            <td class="stat-cell"><div class="form-dots">${formDots}</div></td>
        </tr>`;
    });
    formTableHtml += `</tbody></table></div></div>`;

    return {
        html: `
        <div class="charts-grid charts-grid--wide">
            ${formTableHtml}
        </div>
        <div class="charts-grid charts-grid--wide">
            <div class="chart-wrapper chart-wrapper--wide"><h3 class="chart-title">Points by Round (Top 6)</h3><div class="chart-container chart-container--tall"><canvas id="pointsProgressionChart"></canvas></div></div>
        </div>
        <div class="charts-grid">
            <div class="chart-wrapper"><h3 class="chart-title">Goals by Round</h3><div class="chart-container"><canvas id="goalsPerRoundChart"></canvas></div></div>
            <div class="chart-wrapper"><h3 class="chart-title">Results: Home vs Away</h3><div class="chart-container"><canvas id="homeAwayChart"></canvas></div></div>
        </div>
        <div class="charts-grid">
            <div class="chart-wrapper"><h3 class="chart-title">Goals Scored vs Conceded (Top 10)</h3><div class="chart-container"><canvas id="goalsChart"></canvas></div></div>
            <div class="chart-wrapper"><h3 class="chart-title">Home vs Away Performance (pts)</h3><div class="chart-container"><canvas id="homeAwayPtsChart"></canvas></div></div>
        </div>`,
        goalsData,
        performanceData
    };
}

/**
 * Renders the market values tab with KPIs, filters, table and charts.
 *
 * @returns {string} Full tab HTML
 */
function renderMarketValues() {
    const allPlayers = MARKET_VALUES_DATA.players;

    if (!allPlayers || allPlayers.length === 0) {
        return `<div class="market-empty">
            <div class="market-empty-icon">\uD83D\uDCB0</div>
            <div class="market-empty-title">Market Values</div>
            <div style="font-size:13px">Data is loading. Coming soon!</div>
        </div>`;
    }

    // Apply the header team filter
    const headerTeam = appState.selectedTeam;
    const players    = headerTeam !== 'All teams'
        ? allPlayers.filter(p => p.team === headerTeam)
        : allPlayers;

    if (players.length === 0) {
        return `<div class="market-empty">
            <div class="market-empty-icon">\uD83D\uDD0D</div>
            <div class="market-empty-title">${headerTeam}</div>
            <div style="font-size:13px">No players found for this team in the dataset.</div>
        </div>`;
    }

    const sorted = [...players].sort((a, b) => {
        const col = appState.mercadoSort || 'value';
        const dir = appState.mercadoSortDir === 'asc' ? 1 : -1;
        const va = a[col] ?? '';
        const vb = b[col] ?? '';
        if (typeof va === 'number') return (va - vb) * dir;
        return String(va).localeCompare(String(vb), 'pt-BR') * dir;
    });
    const teams = [...new Set(allPlayers.map(p => p.team))].sort();
    const positions = [...new Set(players.map(p => p.position))].sort();

    // Market KPIs, dynamic based on the filter
    const mostValuable = [...players].sort((a, b) => b.value - a.value)[0];
    const totalValue = players.reduce((s, p) => s + p.value, 0);
    const avgAge = players.length > 0 ? (players.reduce((s, p) => s + p.age, 0) / players.length).toFixed(1).replace('.', ',') : '-';

    let kpiHtml;
    if (headerTeam !== 'All teams') {
        // KPIs for the selected team
        kpiHtml = `<div class="kpi-grid">
            <div class="kpi-card"><div class="kpi-label">Most Valuable Player</div><div class="kpi-value small">${mostValuable.name}</div><div class="kpi-detail" style="color:var(--accent-green)">${formatMarketValue(mostValuable.value)}</div></div>
            <div class="kpi-card"><div class="kpi-label">Squad Value</div><div class="kpi-value small">${formatMarketValue(totalValue)}</div><div class="kpi-detail">${formatMarketValueBRL(totalValue)}</div></div>
            <div class="kpi-card"><div class="kpi-label">Average Age</div><div class="kpi-value">${avgAge}</div><div class="kpi-detail">years</div></div>
            <div class="kpi-card"><div class="kpi-label">Players</div><div class="kpi-value">${players.length}</div></div>
        </div>`;
    } else {
        // League-wide KPIs
        const teamValues = {};
        allPlayers.forEach(p => { teamValues[p.team] = (teamValues[p.team] || 0) + p.value; });
        const teamValArr = Object.entries(teamValues).sort((a, b) => b[1] - a[1]);
        const totalLeagueValue = allPlayers.reduce((s, p) => s + p.value, 0);
        kpiHtml = `<div class="kpi-grid">
            <div class="kpi-card"><div class="kpi-label">Most Valuable Player</div><div class="kpi-value small">${mostValuable.name}</div><div class="kpi-detail" style="color:var(--accent-green)">${formatMarketValue(mostValuable.value)} • ${mostValuable.team}</div></div>
            <div class="kpi-card"><div class="kpi-label">Most Valuable Squad</div><div class="kpi-value small">${teamValArr[0][0]}</div><div class="kpi-detail" style="color:var(--accent-green)">${formatMarketValue(teamValArr[0][1])}</div></div>
            <div class="kpi-card"><div class="kpi-label">Total League Value</div><div class="kpi-value small">${formatMarketValue(totalLeagueValue)}</div></div>
            <div class="kpi-card"><div class="kpi-label">Registered Players</div><div class="kpi-value">${allPlayers.length}</div></div>
        </div>`;
    }
    let html = kpiHtml;

    // Filters
    html += `<div class="market-controls">
        <input type="text" class="market-search" id="playerSearch" placeholder="Buscar jogador...">
        <select class="market-select" id="positionFilter"><option value="">All positions</option>${positions.map(p => `<option value="${p}">${p}</option>`).join('')}</select>
        <select class="market-select" id="marketTeamFilter"><option value="">All teams</option>${teams.map(t => `<option value="${t}">${t}</option>`).join('')}</select>
    </div>`;

    // Players table
    html += `<div class="market-table-wrapper"><table class="market-table" id="marketTable"><thead><tr>
        <th>#</th>
        <th class="sort-th" data-col="name">Player <span class="sort-icon">↕</span></th>
        <th class="sort-th th-center" data-col="team">Team <span class="sort-icon">↕</span></th>
        <th class="sort-th th-center" data-col="position">Pos <span class="sort-icon">↕</span></th>
        <th class="sort-th th-center" data-col="age">Age <span class="sort-icon">↕</span></th>
        <th class="sort-th th-center" data-col="value">Value (EUR) <span class="sort-icon">↕</span></th>
        <th class="th-center">Value (BRL)</th>
    </tr></thead><tbody>`;

    sorted.forEach((p, i) => {
        html += `<tr data-name="${p.name.toLowerCase()}" data-team="${p.team}" data-position="${p.position}">
            <td class="market-rank">${i + 1}</td>
            <td style="font-weight:500">${p.name}</td>
            <td class="stat-cell">${p.team}</td>
            <td class="stat-cell"><span class="market-position-badge">${p.position}</span></td>
            <td class="stat-cell">${p.age}</td>
            <td class="market-value-cell">${formatMarketValue(p.value)}</td>
            <td class="market-value-brl">${formatMarketValueBRL(p.value)}</td>
        </tr>`;
    });

    html += `</tbody></table></div>`;
    const rateNote = MARKET_VALUES_DATA.eur_brl_rate
        ? `Câmbio EUR/BRL: R$ ${MARKET_VALUES_DATA.eur_brl_rate.toFixed(2)}`
        : `Câmbio fixo: R$ ${EUR_TO_BRL.toFixed(2)}`;
    html += `<div class="market-source">Source: ${MARKET_VALUES_DATA.source} | Updated ${MARKET_VALUES_DATA.last_updated || MARKET_VALUES_DATA.lastUpdated} | ${rateNote}</div>`;

    // Charts
    html += `<div class="market-grid" style="margin-top:24px">
        <div class="chart-wrapper"><h3 class="chart-title">Squad Value by Team</h3><div class="chart-container"><canvas id="teamValuesChart"></canvas></div></div>
        <div class="chart-wrapper"><h3 class="chart-title">Distribution by Position</h3><div class="chart-container"><canvas id="positionValuesChart"></canvas></div></div>
    </div>`;

    return html;
}

/**
 * Renders the dedicated tab for a selected team.
 * Includes: team header, KPIs, squad, results, home/away, upcoming matches, points chart.
 */
function renderTimeContent() {
    const teamName = appState.selectedTeam;
    if (teamName === 'All teams') return '';

    const standings = appState.standings || [];
    const t = standings.find(s => s.name === teamName);
    if (!t) return `<div class="historico-empty">Team "${teamName}" not found.</div>`;

    let html = '';

    // ── A. Team header ────────────────────────────────────────
    let zoneName = '', zoneColor = '';
    if (t.position <= 4)       { zoneName = 'Libertadores'; zoneColor = 'var(--zone-lib)'; }
    else if (t.position === 5) { zoneName = 'Libertadores qualifiers'; zoneColor = 'var(--zone-pre-lib)'; }
    else if (t.position <= 11) { zoneName = 'Sudamericana'; zoneColor = 'var(--zone-sul)'; }
    else if (t.position >= 17) { zoneName = 'Relegation'; zoneColor = 'var(--zone-rel)'; }
    else                       { zoneName = 'Mid-table'; zoneColor = 'var(--text-muted)'; }

    html += `<div class="time-header">
        <div class="time-header-info">
            <img src="${t.badge || ''}" alt="${t.name}" class="time-header-badge" onerror="this.style.display='none'">
            <div>
                <h2 class="time-header-name">${t.name}</h2>
                <div class="time-header-meta">
                    <span class="time-position-badge" style="background:${zoneColor}">${t.position}</span>
                    <span style="color:${zoneColor}">${zoneName}</span>
                </div>
            </div>
        </div>
        <button class="time-voltar" id="timeVoltarBtn">\u2190 Back</button>
    </div>`;

    // ── B. Team KPIs ──────────────────────────────────────────
    const maxPts    = t.played * 3 || 1;
    const aprov     = Math.round(t.points / maxPts * 100);
    const sg        = t.goalsFor - t.goalsAgainst;
    const sgStr     = sg > 0 ? `+${sg}` : String(sg);
    const sgColor   = sg > 0 ? 'var(--accent-green)' : sg < 0 ? 'var(--accent-red)' : 'var(--text-secondary)';
    const aprovColor = aprov >= 60 ? 'var(--accent-green)' : aprov >= 40 ? 'var(--accent-yellow)' : 'var(--accent-red)';

    html += `<div class="kpi-grid" style="margin-bottom:24px">
        <div class="kpi-card"><div class="kpi-label">Points</div><div class="kpi-value">${t.points}</div><div class="kpi-detail">${t.played} played</div></div>
        <div class="kpi-card"><div class="kpi-label">Points %</div><div class="kpi-value" style="color:${aprovColor}">${aprov}%</div><div class="kpi-detail">${t.wins}W ${t.draws}D ${t.losses}L</div></div>
        <div class="kpi-card"><div class="kpi-label">Goals</div><div class="kpi-value">${t.goalsFor}<span style="font-size:14px;color:var(--text-muted)"> / ${t.goalsAgainst}</span></div><div class="kpi-detail">For / Against</div></div>
        <div class="kpi-card"><div class="kpi-label">Goal Difference</div><div class="kpi-value" style="color:${sgColor}">${sgStr}</div><div class="kpi-detail">Position: ${t.position}</div></div>
    </div>`;

    // ── C. Goals per match chart ────────────────────────────────
    html += `<div class="charts-grid" style="margin-bottom:24px">
        <div class="chart-wrapper" style="grid-column:1/-1">
            <h3 class="chart-title">Goals per Match</h3>
            <div class="chart-container"><canvas id="timeGoalsPerMatchChart"></canvas></div>
        </div>
    </div>`;

    // ── D. Results (every match played) ────────────────
    const allMatchesForTeam = appState.allMatches.filter(m =>
        (m.strHomeTeam === teamName || m.strAwayTeam === teamName)
        && m.intHomeScore !== null && m.intHomeScore !== undefined && m.intHomeScore !== ''
    ).sort((a, b) => parseInt(a.intRound) - parseInt(b.intRound));

    if (allMatchesForTeam.length > 0) {
        html += `<h3 class="section-title">Results</h3>`;
        html += `<div class="charts-grid" style="margin-bottom:24px">
            <div class="chart-wrapper" style="grid-column:1/-1">
                <div class="market-table-wrapper"><table class="market-table">
                    <thead><tr><th class="th-center">R</th><th class="th-center">Date</th><th>Opponent</th><th class="th-center">Venue</th><th class="th-center">Score</th><th class="th-center">Res.</th></tr></thead>
                    <tbody>${allMatchesForTeam.map(m => {
                        const isHome = m.strHomeTeam === teamName;
                        const opponent = isHome ? m.strAwayTeam : m.strHomeTeam;
                        const opBadge = isHome ? m.strAwayTeamBadge : m.strHomeTeamBadge;
                        const hs = parseInt(m.intHomeScore) || 0;
                        const as = parseInt(m.intAwayScore) || 0;
                        const teamGoals = isHome ? hs : as;
                        const oppGoals = isHome ? as : hs;
                        const res = teamGoals > oppGoals ? 'W' : teamGoals === oppGoals ? 'D' : 'L';
                        const resColor = res === 'W' ? 'var(--accent-green)' : res === 'D' ? 'var(--accent-yellow)' : 'var(--accent-red)';
                        const where = isHome ? '\uD83C\uDFE0' : '\u2708\uFE0F';
                        return `<tr>
                            <td class="stat-cell">${m.intRound}</td>
                            <td class="stat-cell">${formatDateShort(m.dateEvent)}</td>
                            <td><div style="display:flex;align-items:center;gap:6px"><img src="${opBadge || ''}" class="team-logo" onerror="this.style.display='none'"><span>${opponent}</span></div></td>
                            <td class="stat-cell">${where}</td>
                            <td class="stat-cell" style="font-weight:600">${teamGoals} × ${oppGoals}</td>
                            <td style="text-align:center;font-weight:700;color:${resColor}">${res}</td>
                        </tr>`;
                    }).join('')}</tbody>
                </table></div>
            </div>
        </div>`;
    }

    // ── E. Home vs Away ──────────────────────────────────────────
    html += `<div class="charts-grid" style="margin-bottom:24px">
        <div class="chart-wrapper">
            <h3 class="chart-title">Home vs Away</h3>
            <div class="market-table-wrapper"><table class="market-table">
                <thead><tr><th>Venue</th><th class="th-center">P</th><th class="th-center">W</th><th class="th-center">D</th><th class="th-center">L</th><th class="th-center">GF</th><th class="th-center">GA</th><th class="th-center">Pts</th></tr></thead>
                <tbody>
                    <tr>
                        <td style="font-weight:600">\uD83C\uDFE0 Home</td>
                        <td class="stat-cell">${t.homeWins+t.homeDraws+t.homeLosses}</td>
                        <td class="stat-cell">${t.homeWins}</td>
                        <td class="stat-cell">${t.homeDraws}</td>
                        <td class="stat-cell">${t.homeLosses}</td>
                        <td class="stat-cell">${t.homeGoalsFor}</td>
                        <td class="stat-cell">${t.homeGoalsAgainst}</td>
                        <td class="points-cell">${t.homeWins*3+t.homeDraws}</td>
                    </tr>
                    <tr>
                        <td style="font-weight:600">\u2708\uFE0F Away</td>
                        <td class="stat-cell">${t.awayWins+t.awayDraws+t.awayLosses}</td>
                        <td class="stat-cell">${t.awayWins}</td>
                        <td class="stat-cell">${t.awayDraws}</td>
                        <td class="stat-cell">${t.awayLosses}</td>
                        <td class="stat-cell">${t.awayGoalsFor}</td>
                        <td class="stat-cell">${t.awayGoalsAgainst}</td>
                        <td class="points-cell">${t.awayWins*3+t.awayDraws}</td>
                    </tr>
                </tbody></table></div>
        </div>
        <div class="chart-wrapper">
            <h3 class="chart-title">Points Progression</h3>
            <div class="chart-container chart-container--tall"><canvas id="timePointsChart"></canvas></div>
        </div>
    </div>`;

    // ── F. Upcoming matches ────────────────────────────────────────
    html += renderProximosJogos(appState.allMatches, teamName);

    return html;
}

/**
 * Initialises the Team tab charts (points progression + goals per match).
 */
function initTimeChart() {
    // Goals per match chart
    const goalsCtx = document.getElementById('timeGoalsPerMatchChart');
    if (goalsCtx && !goalsCtx._chartInit) {
        goalsCtx._chartInit = true;
        const teamName = appState.selectedTeam;
        const matches = appState.allMatches.filter(m =>
            (m.strHomeTeam === teamName || m.strAwayTeam === teamName)
            && m.intHomeScore !== null && m.intHomeScore !== undefined && m.intHomeScore !== ''
        ).sort((a, b) => parseInt(a.intRound) - parseInt(b.intRound));

        const labels = matches.map(m => `R${m.intRound}`);
        const goalsFor = matches.map(m => {
            const isHome = m.strHomeTeam === teamName;
            return isHome ? parseInt(m.intHomeScore) || 0 : parseInt(m.intAwayScore) || 0;
        });
        const goalsAgainst = matches.map(m => {
            const isHome = m.strHomeTeam === teamName;
            return isHome ? parseInt(m.intAwayScore) || 0 : parseInt(m.intHomeScore) || 0;
        });

        appState.chartInstances.push(new Chart(goalsCtx, {
            type: 'bar',
            data: {
                labels,
                datasets: [
                    { label: 'Goals Scored', data: goalsFor, backgroundColor: '#10b981', borderRadius: 3 },
                    { label: 'Goals Conceded', data: goalsAgainst, backgroundColor: '#ef4444', borderRadius: 3 }
                ]
            },
            options: {
                responsive: true, maintainAspectRatio: false,
                plugins: { legend: { labels: { color: '#8b949e', font: { family: "'Inter'", size: 11 } } }, tooltip: TOOLTIP_STYLE },
                scales: {
                    x: { grid: { display: false }, ticks: { color: '#8b949e', font: { size: 10 } } },
                    y: { grid: { color: '#21262d' }, ticks: { color: '#8b949e', font: { size: 10 } }, beginAtZero: true }
                }
            }
        }));
    }

    // Points progression chart
    const ctx = document.getElementById('timePointsChart');
    if (!ctx || ctx._chartInit) return;
    ctx._chartInit = true;

    const teamName = appState.selectedTeam;
    const standings = appState.standings || [];
    const leader = standings[0];
    if (!leader) return;

    const { rounds, series } = buildPointsProgression(appState.allMatches);
    const teamSeries = series[teamName] || [];
    const leaderSeries = series[leader.name] || [];

    appState.chartInstances.push(new Chart(ctx, {
        type: 'line',
        data: {
            labels: rounds.map(r => `R${r}`),
            datasets: [
                {
                    label: teamName,
                    data: teamSeries,
                    borderColor: '#10b981',
                    backgroundColor: 'rgba(16,185,129,0.1)',
                    borderWidth: 2.5,
                    pointRadius: 4,
                    pointBackgroundColor: '#10b981',
                    fill: true,
                    tension: 0.3,
                },
                ...(leader.name !== teamName ? [{
                    label: `${leader.name} (Leader)`,
                    data: leaderSeries,
                    borderColor: '#6b7280',
                    borderWidth: 1.5,
                    borderDash: [5, 3],
                    pointRadius: 2,
                    pointBackgroundColor: '#6b7280',
                    fill: false,
                    tension: 0.3,
                }] : [])
            ]
        },
        options: {
            responsive: true,
            maintainAspectRatio: false,
            plugins: {
                legend: { labels: { font: { family: "'Inter', sans-serif", size: 11 }, color: '#8b949e' } }
            },
            scales: {
                x: { grid: { color: '#21262d' }, ticks: { color: '#8b949e', font: { size: 10 } } },
                y: { grid: { color: '#21262d' }, ticks: { color: '#8b949e', font: { size: 10 } }, beginAtZero: true }
            }
        }
    }));
}

/**
 * Renders the upcoming fixtures section.
 */
function renderProximosJogos(allMatches, selectedTeam) {
    const hoje = new Date();
    hoje.setHours(0, 0, 0, 0);

    let proximos = allMatches.filter(m =>
        (m.intHomeScore === null || m.intHomeScore === undefined || m.intHomeScore === '')
        && new Date(m.dateEvent + 'T23:59:59') >= hoje
    );

    if (selectedTeam !== 'All teams') {
        proximos = proximos.filter(m =>
            m.strHomeTeam === selectedTeam || m.strAwayTeam === selectedTeam
        );
    }

    proximos.sort((a, b) => new Date(a.dateEvent) - new Date(b.dateEvent));
    proximos = proximos.slice(0, 10);

    if (proximos.length === 0) return '';

    let html = '<h3 class="section-title">Upcoming Matches</h3><div class="rodada-wrapper"><div class="rodada-list">';
    proximos.forEach(m => {
        const rodada = m.intRound ? `R${m.intRound}` : '';
        const data = formatDateShort(m.dateEvent);
        html += `<div class="fixture-row">
            <div class="fixture-row-teams">
                <img src="${m.strHomeTeamBadge || ''}" alt="" class="team-logo" onerror="this.style.display='none'">
                <span>${m.strHomeTeam}</span>
                <span class="fixture-row-x">×</span>
                <img src="${m.strAwayTeamBadge || ''}" alt="" class="team-logo" onerror="this.style.display='none'">
                <span>${m.strAwayTeam}</span>
            </div>
            <div class="fixture-row-meta">${rodada} • ${data}</div>
        </div>`;
    });
    html += '</div></div>';
    return html;
}


/**
 * Renders the results for a specific round.
 */
function renderResultadosRodada(allMatches, latestRound) {
    const played = allMatches.filter(m =>
        m.intHomeScore !== null && m.intHomeScore !== undefined && m.intHomeScore !== ''
    );
    if (played.length === 0) return '';

    const rounds = [...new Set(played.map(m => parseInt(m.intRound)))].sort((a, b) => a - b);
    const currentRound = latestRound || rounds[rounds.length - 1];

    let options = rounds.map(r =>
        `<option value="${r}" ${r === currentRound ? 'selected' : ''}>Round ${r}</option>`
    ).join('');

    const roundMatches = allMatches.filter(m => parseInt(m.intRound) === currentRound);

    let matchesHtml = '';
    roundMatches.forEach(m => {
        const hs = m.intHomeScore !== null && m.intHomeScore !== '' ? parseInt(m.intHomeScore) : null;
        const as_ = m.intAwayScore !== null && m.intAwayScore !== '' ? parseInt(m.intAwayScore) : null;
        const played_ = hs !== null;
        const scoreHtml = played_
            ? `<span class="rodada-score">${hs} – ${as_}</span>`
            : `<span class="rodada-date">${formatDateShort(m.dateEvent)}</span>`;

        matchesHtml += `<div class="rodada-match">
            <div class="rodada-team rodada-team--home">
                <span>${m.strHomeTeam}</span>
                <img src="${m.strHomeTeamBadge || ''}" class="team-logo" onerror="this.style.display='none'">
            </div>
            ${scoreHtml}
            <div class="rodada-team rodada-team--away">
                <img src="${m.strAwayTeamBadge || ''}" class="team-logo" onerror="this.style.display='none'">
                <span>${m.strAwayTeam}</span>
            </div>
        </div>`;
    });

    return `<div class="rodada-wrapper" style="margin-top:24px">
        <div class="rodada-header">
            <span class="rodada-header-title">Results</span>
            <select class="rodada-select" id="roundSelector">${options}</select>
        </div>
        <div class="rodada-list">${matchesHtml}</div>
    </div>`;
}

/**
 * Renders the points % ranking with visual bars.
 */
function renderRankingAproveitamento(standings) {
    if (!standings || standings.length === 0) return '';

    const sorted = [...standings].sort((a, b) => {
        const pa = a.played > 0 ? a.points / (a.played * 3) : 0;
        const pb = b.played > 0 ? b.points / (b.played * 3) : 0;
        return pb - pa;
    });

    let rows = sorted.map((t, i) => {
        const pct = t.played > 0 ? Math.round(t.points / (t.played * 3) * 100) : 0;
        const color = pct >= 60 ? 'var(--accent-green)' : pct >= 40 ? 'var(--accent-yellow)' : 'var(--accent-red)';
        return `<tr>
            <td class="position-cell">${i + 1}</td>
            <td class="team-cell"><span class="team-name">${t.name}</span></td>
            <td class="stat-cell">${t.played}</td>
            <td class="stat-cell">${t.points}</td>
            <td class="stat-cell" style="min-width:120px">
                <div style="display:flex;align-items:center;gap:8px">
                    <div style="flex:1;height:6px;background:rgba(255,255,255,0.06);border-radius:3px;overflow:hidden">
                        <div style="width:${pct}%;height:100%;background:${color};border-radius:3px"></div>
                    </div>
                    <span style="font-weight:700;color:${color};min-width:36px;text-align:right">${pct}%</span>
                </div>
            </td>
        </tr>`;
    }).join('');

    return `<div class="chart-wrapper" style="grid-column:1/-1">
        <h3 class="chart-title">Points % Ranking</h3>
        <div class="market-table-wrapper"><table class="standings-table">
            <thead><tr><th>#</th><th>Team</th><th class="th-center">P</th><th class="th-center">Pts</th><th class="th-center">Points %</th></tr></thead>
            <tbody>${rows}</tbody>
        </table></div>
    </div>`;
}

/**
 * Renders the results heatmap (round × team).
 */
function renderHeatmap(standings, allMatches) {
    if (!standings || standings.length === 0) return '';

    const played = allMatches.filter(m =>
        m.intHomeScore !== null && m.intHomeScore !== undefined && m.intHomeScore !== ''
    );
    const rounds = [...new Set(played.map(m => parseInt(m.intRound)))].sort((a, b) => a - b);
    if (rounds.length === 0) return '';

    // Build result map: team -> round -> {result, opponent, score}
    const resultMap = {};
    standings.forEach(t => { resultMap[t.name] = {}; });
    played.forEach(m => {
        const r = parseInt(m.intRound);
        const hs = parseInt(m.intHomeScore) || 0;
        const as_ = parseInt(m.intAwayScore) || 0;
        const homeRes = hs > as_ ? 'W' : hs === as_ ? 'D' : 'L';
        const awayRes = hs < as_ ? 'W' : hs === as_ ? 'D' : 'L';
        if (resultMap[m.strHomeTeam]) {
            resultMap[m.strHomeTeam][r] = { res: homeRes, opp: m.strAwayTeam, score: `${hs}-${as_}` };
        }
        if (resultMap[m.strAwayTeam]) {
            resultMap[m.strAwayTeam][r] = { res: awayRes, opp: m.strHomeTeam, score: `${as_}-${hs}` };
        }
    });

    let headerCells = rounds.map(r => `<th class="heatmap-th">${r}</th>`).join('');
    let bodyRows = standings.map(t => {
        let cells = rounds.map(r => {
            const d = resultMap[t.name][r];
            if (!d) return '<td class="heatmap-cell"></td>';
            const cls = d.res === 'W' ? 'heatmap-win' : d.res === 'D' ? 'heatmap-draw' : 'heatmap-loss';
            return `<td class="heatmap-cell ${cls}" title="${t.name} ${d.score} ${d.opp}">${d.res}</td>`;
        }).join('');
        return `<tr><td class="heatmap-team">${t.name}</td>${cells}</tr>`;
    }).join('');

    return `<div class="chart-wrapper" style="grid-column:1/-1">
        <h3 class="chart-title">Results Map</h3>
        <div class="heatmap-wrapper"><table class="heatmap-table">
            <thead><tr><th class="heatmap-team-th">Team</th>${headerCells}</tr></thead>
            <tbody>${bodyRows}</tbody>
        </table></div>
    </div>`;
}

/**
 * Renders the historical comparison section (lazy load).
 */
function renderHistorico() {
    const hist = window.HISTORICO_DATA;
    if (!hist) {
        // Trigger lazy load
        if (!window._loadingHistorico) {
            window._loadingHistorico = true;
            fetch('data/historico.json')
                .then(r => r.ok ? r.json() : null)
                .then(d => {
                    window.HISTORICO_DATA = d;
                    window._loadingHistorico = false;
                    // Re-render if the tab is active
                    if (appState.activeTab === 'estatisticas') render();
                })
                .catch(() => { window._loadingHistorico = false; });
        }
        return `<div class="chart-wrapper" style="grid-column:1/-1">
            <h3 class="chart-title">Historical Comparison</h3>
            <div style="text-align:center;padding:20px;color:var(--text-muted);font-size:12px">Loading historical data...</div>
        </div>`;
    }

    const currentRound = appState.selectedRound || 1;
    const seasons = hist.seasons || [];
    const lastSeason = seasons[seasons.length - 1];
    const prevStandings = hist.standings_by_season[lastSeason] || [];
    const prevLeader = prevStandings[0];

    const currentLeader = (appState.standings || [])[0];

    // Top 5 all-time scorers
    const topScorers = (hist.scorers_all_time || []).slice(0, 5);

    let html = `<div class="chart-wrapper" style="grid-column:1/-1">
        <h3 class="chart-title">Historical Comparison</h3>
        <div class="kpi-grid" style="margin-bottom:16px">
            <div class="kpi-card">
                <div class="kpi-label">Current leader (R${currentRound})</div>
                <div class="kpi-value small">${currentLeader ? currentLeader.name : '-'}</div>
                <div class="kpi-detail">${currentLeader ? currentLeader.points + ' pts' : ''}</div>
            </div>
            <div class="kpi-card">
                <div class="kpi-label">Champion ${lastSeason}</div>
                <div class="kpi-value small">${prevLeader ? prevLeader.team : '-'}</div>
                <div class="kpi-detail">${prevLeader ? prevLeader.points + ' pts in 38 rounds' : ''}</div>
            </div>
        </div>`;

    if (topScorers.length > 0) {
        html += `<h4 style="font-size:11px;font-weight:600;color:var(--text-muted);text-transform:uppercase;letter-spacing:0.5px;margin-bottom:8px">Brasileirão All-Time Top Scorers</h4>
        <div class="market-table-wrapper"><table class="market-table">
            <thead><tr><th>#</th><th>Player</th><th class="th-center">Club</th><th class="th-center">Goals</th></tr></thead>
            <tbody>${topScorers.map((s, i) => `<tr>
                <td class="market-rank">${i + 1}</td>
                <td style="font-weight:500">${s.player}</td>
                <td class="stat-cell">${s.club}</td>
                <td style="text-align:center;font-weight:700;color:var(--accent-green)">${s.goals}</td>
            </tr>`).join('')}</tbody>
        </table></div>`;
    }

    html += '</div>';
    return html;
}

/** Renders the loading screen */
function renderLoading() {
    return '<div class="loading-container"><div class="spinner"></div><div class="loading-text">Loading Brasileirão data...</div></div>';
}

/**
 * Renders the error screen with a retry button.
 * @param {string} message - Error message
 */
function renderError(message) {
    return `<div class="error-container"><div class="error-message">
        <div class="error-icon">\u26A0\uFE0F</div>
        <div class="error-title">Error Loading Data</div>
        <div class="error-text">${message}</div>
        <button class="btn-retry" id="retryBtn">Try Again</button>
    </div></div>`;
}


/* ============================================================================
 * SECTION 5: CHART INITIALISATION
 * ============================================================================ */

/**
 * Base configuration shared by every Chart.js chart.
 * @type {Object}
 */
/** Custom tooltip shared by every chart */
const TOOLTIP_STYLE = {
    backgroundColor: '#161b22',
    titleColor: '#e6edf3',
    bodyColor: '#8b949e',
    borderColor: '#30363d',
    borderWidth: 1,
    padding: 10,
    cornerRadius: 6,
    titleFont: { family: "'Inter', sans-serif", weight: '600', size: 12 },
    bodyFont: { family: "'Inter', sans-serif", size: 11 },
    displayColors: true,
    boxPadding: 4,
};

const BASE_CHART_OPTIONS = {
    indexAxis: 'y',
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
        legend: {
            labels: {
                font: { family: "'Inter', sans-serif", size: 11 },
                color: '#8b949e'
            }
        },
        tooltip: TOOLTIP_STYLE,
    },
    scales: {
        x: {
            grid: { color: '#21262d', drawBorder: false },
            ticks: { color: '#8b949e', font: { family: "'Inter', sans-serif", size: 10 } }
        },
        y: {
            grid: { display: false },
            ticks: { color: '#8b949e', font: { family: "'Inter', sans-serif", size: 10 } }
        }
    }
};

/**
 * Initialises the market values tab charts.
 * Uses a _chartInit flag on the canvas to avoid duplication.
 */
function initMarketCharts() {
    const players = MARKET_VALUES_DATA.players;
    if (!players || players.length === 0) return;

    // Value by team
    const teamValues = {};
    players.forEach(p => { teamValues[p.team] = (teamValues[p.team] || 0) + p.value; });
    const teamValArr = Object.entries(teamValues).sort((a, b) => b[1] - a[1]);

    // Value by position
    const posValues = {};
    players.forEach(p => { posValues[p.position] = (posValues[p.position] || 0) + p.value; });
    const posValArr = Object.entries(posValues).sort((a, b) => b[1] - a[1]);

    const tvCtx = document.getElementById('teamValuesChart');
    if (tvCtx && !tvCtx._chartInit) {
        tvCtx._chartInit = true;
        appState.chartInstances.push(new Chart(tvCtx, {
            type: 'bar',
            data: {
                labels: teamValArr.map(t => t[0]),
                datasets: [{ data: teamValArr.map(t => t[1]), backgroundColor: '#059669', borderRadius: 4 }]
            },
            options: {
                ...BASE_CHART_OPTIONS,
                plugins: { legend: { display: false } },
                scales: {
                    ...BASE_CHART_OPTIONS.scales,
                    x: {
                        ...BASE_CHART_OPTIONS.scales.x,
                        ticks: {
                            ...BASE_CHART_OPTIONS.scales.x.ticks,
                            callback: v => v >= 1e6 ? (v / 1e6).toFixed(0) + 'M' : v
                        }
                    }
                }
            }
        }));
    }

    const pvCtx = document.getElementById('positionValuesChart');
    if (pvCtx && !pvCtx._chartInit) {
        pvCtx._chartInit = true;
        const colors = ['#059669', '#2563eb', '#d97706', '#dc2626', '#8b5cf6', '#ec4899', '#06b6d4', '#84cc16', '#f97316', '#6366f1'];
        appState.chartInstances.push(new Chart(pvCtx, {
            type: 'doughnut',
            data: {
                labels: posValArr.map(p => p[0]),
                datasets: [{ data: posValArr.map(p => p[1]), backgroundColor: colors.slice(0, posValArr.length) }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        position: 'right',
                        labels: { font: { family: "'Inter', sans-serif", size: 11 }, color: '#8b949e' }
                    }
                }
            }
        }));
    }
}


/* ============================================================================
 * SECTION 6: MAIN RENDER AND EVENT LISTENERS
 * ============================================================================ */

/**
 * Attaches sort and filter listeners to the Market table.
 * Can be called after render() and when switching tabs.
 */
function attachMercadoSortListeners() {
    const playerSearch = document.getElementById('playerSearch');
    const posFilter    = document.getElementById('positionFilter');
    const mktTeamFilter = document.getElementById('marketTeamFilter');

    if (playerSearch) {
        const filterMarket = () => {
            const query = playerSearch.value.toLowerCase();
            const pos   = posFilter.value;
            const team  = mktTeamFilter.value;
            document.querySelectorAll('#marketTable tbody tr').forEach(tr => {
                const nameMatch = !query || tr.dataset.name.includes(query);
                const posMatch  = !pos  || tr.dataset.position === pos;
                const teamMatch = !team || tr.dataset.team === team;
                tr.style.display = (nameMatch && posMatch && teamMatch) ? '' : 'none';
            });
        };
        playerSearch.addEventListener('input', filterMarket);
        posFilter.addEventListener('change', filterMarket);
        mktTeamFilter.addEventListener('change', filterMarket);
    }

    document.querySelectorAll('.sort-th').forEach(th => {
        th.addEventListener('click', () => {
            const col = th.dataset.col;
            if (appState.mercadoSort === col) {
                appState.mercadoSortDir = appState.mercadoSortDir === 'desc' ? 'asc' : 'desc';
            } else {
                appState.mercadoSort    = col;
                appState.mercadoSortDir = col === 'name' || col === 'team' || col === 'position' ? 'asc' : 'desc';
            }
            const tabDiv = document.getElementById('tab-mercado');
            if (tabDiv) {
                tabDiv.innerHTML = renderMarketValues();
                attachMercadoSortListeners();
            }
        });
    });
}

/**
 * Main render function.
 * Builds all the dashboard HTML, injects it into the DOM and sets up event listeners.
 * Called after loading data and when filters change.
 */
function render() {
    const appDiv = document.getElementById('app');
    const { selectedTeam, selectedRound: selRound, activeTab } = appState;
    const selectedRound = selRound || 1;
    const latestRound = appState.allMatches.length > 0
        ? Math.max(...appState.allMatches.map(m => parseInt(m.intRound)))
        : 1;

    // === BUILD THE HTML ===
    let html = renderHeader(latestRound, selectedTeam, selectedRound, appState.lastUpdated);

    // Tab bar
    const timeLabel = selectedTeam !== 'All teams' ? selectedTeam : 'Team';
    html += `<div class="tab-bar"><div class="tab-bar-inner">
        <button class="tab-btn ${activeTab === 'tabela' ? 'active' : ''}" data-tab="tabela">Table</button>
        <button class="tab-btn ${activeTab === 'estatisticas' ? 'active' : ''}" data-tab="estatisticas">Stats</button>
        <button class="tab-btn ${activeTab === 'mercado' ? 'active' : ''}" data-tab="mercado">Market</button>
        <button class="tab-btn ${activeTab === 'time' ? 'active' : ''}" data-tab="time">${timeLabel}</button>
    </div></div>`;

    html += '<div class="container">';

    // Tab: Table (league KPIs + standings)
    html += `<div class="tab-content ${activeTab === 'tabela' ? 'active' : ''}" id="tab-tabela">`;
    html += renderKPIs(appState.standings, appState.allMatches);
    html += renderProximosJogos(appState.allMatches, appState.selectedTeam);
    html += '<h3 class="section-title">Standings</h3>';
    html += renderStandings(appState.standings, {}, selectedTeam);
    html += renderResultadosRodada(appState.allMatches, appState.selectedRound);
    html += '</div>'; // tab-tabela


    // Tab: Stats (KPIs + top scorers + charts)
    html += `<div class="tab-content ${activeTab === 'estatisticas' ? 'active' : ''}" id="tab-estatisticas">`;
    html += renderEstatisticasContent();
    const chartsRender = renderCharts(appState.standings);
    html += chartsRender.html;
    html += `<div class="charts-grid charts-grid--wide">${renderRankingAproveitamento(appState.standings)}</div>`;
    html += `<div class="charts-grid charts-grid--wide">${renderHeatmap(appState.standings, appState.allMatches)}</div>`;
    html += `<div class="charts-grid charts-grid--wide">${renderHistorico()}</div>`;
    html += '</div>'; // tab-estatisticas

    // Tab: Market
    html += `<div class="tab-content ${activeTab === 'mercado' ? 'active' : ''}" id="tab-mercado">`;
    html += renderMarketValues();
    html += '</div>';

    // Tab: Team
    html += `<div class="tab-content ${activeTab === 'time' ? 'active' : ''}" id="tab-time">`;
    if (selectedTeam !== 'All teams') {
        html += renderTimeContent();
    } else {
        html += `<div class="standings-empty" style="padding:60px 20px">
            <div style="font-size:32px;opacity:0.3;margin-bottom:12px">\uD83C\uDFDF\uFE0F</div>
            <div style="font-size:15px;font-weight:600;color:var(--text-secondary);margin-bottom:6px">Select a team</div>
            <div style="font-size:12px;color:var(--text-muted)">Click a team in the standings table or use the filter at the top.</div>
        </div>`;
    }
    html += '</div>';

    html += `<div class="footer">Data: <a href="https://www.espn.com.br" target="_blank" rel="noopener">ESPN</a> &bull; <a href="https://github.com/dcaribou/transfermarkt-datasets" target="_blank" rel="noopener">Transfermarkt (dcaribou)</a> | Brasileirão Série A ${appState.season || 2026}</div>`;
    html += '</div>'; // container

    appDiv.innerHTML = html;

    // === EVENT LISTENERS ===

    // Team filter
    const teamSelect = document.getElementById('teamFilter');
    (appState.standings || []).forEach(team => {
        const opt = document.createElement('option');
        opt.value = team.name;
        opt.textContent = team.name;
        teamSelect.appendChild(opt);
    });
    teamSelect.value = appState.selectedTeam;
    teamSelect.addEventListener('change', e => {
        appState.selectedTeam = e.target.value;
        render();
    });



    // Theme toggle
    const themeBtn = document.getElementById('themeToggle');
    if (themeBtn) {
        themeBtn.addEventListener('click', () => {
            const current = document.documentElement.getAttribute('data-theme') || 'dark';
            const next = current === 'dark' ? 'light' : 'dark';
            document.documentElement.setAttribute('data-theme', next);
            localStorage.setItem('theme', next);
            themeBtn.textContent = next === 'light' ? '\u2600\uFE0F' : '\uD83C\uDF19';
        });
    }

    // Round selector
    const roundSelector = document.getElementById('roundSelector');
    if (roundSelector) {
        roundSelector.addEventListener('change', e => {
            const round = parseInt(e.target.value);
            const container = document.querySelector('.rodada-list');
            if (!container) return;
            // Re-render only the round section
            const matches = appState.allMatches.filter(m => parseInt(m.intRound) === round);
            container.innerHTML = matches.map(m => {
                const hs = m.intHomeScore !== null && m.intHomeScore !== '' ? parseInt(m.intHomeScore) : null;
                const as_ = m.intAwayScore !== null && m.intAwayScore !== '' ? parseInt(m.intAwayScore) : null;
                const played_ = hs !== null;
                const scoreHtml = played_
                    ? `<span class="rodada-score">${hs} – ${as_}</span>`
                    : `<span class="rodada-date">${formatDateShort(m.dateEvent)}</span>`;
                return `<div class="rodada-match">
                    <div class="rodada-team rodada-team--home"><span>${m.strHomeTeam}</span><img src="${m.strHomeTeamBadge || ''}" class="team-logo" onerror="this.style.display='none'"></div>
                    ${scoreHtml}
                    <div class="rodada-team rodada-team--away"><img src="${m.strAwayTeamBadge || ''}" class="team-logo" onerror="this.style.display='none'"><span>${m.strAwayTeam}</span></div>
                </div>`;
            }).join('');
        });
    }

    // Click on a team in the table → Team tab
    document.querySelectorAll('.standings-table tbody tr').forEach(row => {
        row.style.cursor = 'pointer';
        row.addEventListener('click', () => {
            const nameEl = row.querySelector('.team-name');
            if (nameEl) {
                appState.selectedTeam = nameEl.textContent;
                appState.activeTab = 'time';
                render();
            }
        });
    });

    // Back button on the Team tab
    const voltarBtn = document.getElementById('timeVoltarBtn');
    if (voltarBtn) {
        voltarBtn.addEventListener('click', () => {
            appState.selectedTeam = 'All teams';
            appState.activeTab = 'tabela';
            render();
        });
    }

    // Switch tabs (no re-render, just toggle classes)
    document.querySelectorAll('.tab-btn').forEach(btn => {
        btn.addEventListener('click', e => {
            const tab = e.target.dataset.tab;
            appState.activeTab = tab;
            document.querySelectorAll('.tab-btn').forEach(b =>
                b.classList.toggle('active', b.dataset.tab === tab));
            document.querySelectorAll('.tab-content').forEach(c =>
                c.classList.toggle('active', c.id === 'tab-' + tab));
            if (tab === 'mercado') { initMarketCharts(); attachMercadoSortListeners(); }
            if (tab === 'estatisticas') {
                setTimeout(() => initEstatisticasCharts(chartsRender), 50);
            }
            if (tab === 'time') {
                setTimeout(() => initTimeChart(), 50);
            }
        });
    });

    // Market filters and sorting
    attachMercadoSortListeners();

    // === CHARTS ===

    // Destroy previous instances to avoid a memory leak
    appState.chartInstances.forEach(c => c.destroy());
    appState.chartInstances = [];

    // Initialise charts after a short delay to make sure the DOM is ready
    setTimeout(() => {
        // Only initialise stats charts if the tab is active
        if (activeTab === 'estatisticas') initEstatisticasCharts(chartsRender);

        // Market charts if the tab is active
        if (activeTab === 'mercado') initMarketCharts();

        // Points chart on the Team tab
        if (activeTab === 'time') initTimeChart();
    }, 100);
}

/**
 * Initialises the Stats tab charts.
 * Kept separate from render() so it can be called when switching tabs.
 */
function initEstatisticasCharts(chartsRender) {
    const goalsCtx = document.getElementById('goalsChart');
        if (goalsCtx) {
            appState.chartInstances.push(new Chart(goalsCtx, {
                type: 'bar',
                data: chartsRender.goalsData,
                options: BASE_CHART_OPTIONS
            }));
        }

        const perfCtx = document.getElementById('performanceChart');
        if (perfCtx) {
            appState.chartInstances.push(new Chart(perfCtx, {
                type: 'bar',
                data: chartsRender.performanceData,
                options: {
                    ...BASE_CHART_OPTIONS,
                    plugins: { legend: { display: false } },
                    scales: {
                        ...BASE_CHART_OPTIONS.scales,
                        x: { ...BASE_CHART_OPTIONS.scales.x, max: 100 }
                    }
                }
            }));
        }

        // Points progression
        const ppCtx = document.getElementById('pointsProgressionChart');
        if (ppCtx && !ppCtx._chartInit && appState.allMatches.length > 0) {
            ppCtx._chartInit = true;
            const filtered = getFilteredMatches();
            const { rounds, series } = buildPointsProgression(filtered);
            const top6 = (appState.standings || []).slice(0, 6).map(t => t.name);
            const colors = ['#059669','#2563eb','#d97706','#dc2626','#8b5cf6','#ec4899'];
            appState.chartInstances.push(new Chart(ppCtx, {
                type: 'line',
                data: {
                    labels: rounds.map(r => `R${r}`),
                    datasets: top6.map((name, i) => ({
                        label: name,
                        data: series[name] || [],
                        borderColor: colors[i],
                        backgroundColor: colors[i] + '22',
                        borderWidth: 2,
                        pointRadius: 3,
                        tension: 0.3,
                        fill: false,
                    }))
                },
                options: {
                    responsive: true, maintainAspectRatio: false,
                    plugins: { legend: { labels: { font: { family: "'Inter',sans-serif", size: 11 }, color: '#8b949e' } }, tooltip: TOOLTIP_STYLE },
                    scales: {
                        x: { grid: { color: '#21262d' }, ticks: { color: '#8b949e', font: { size: 10 } } },
                        y: { grid: { color: '#21262d' }, ticks: { color: '#8b949e', font: { size: 10 } }, beginAtZero: true }
                    }
                }
            }));
        }

        // Goals by round
        const gprCtx = document.getElementById('goalsPerRoundChart');
        if (gprCtx && !gprCtx._chartInit && appState.allMatches.length > 0) {
            gprCtx._chartInit = true;
            const filtered = getFilteredMatches();
            const rounds = [...new Set(filtered.map(m => parseInt(m.intRound)))].sort((a,b) => a-b);
            const goalsPerRound = rounds.map(r =>
                filtered.filter(m => parseInt(m.intRound) === r)
                    .reduce((s, m) => s + (parseInt(m.intHomeScore)||0) + (parseInt(m.intAwayScore)||0), 0)
            );
            appState.chartInstances.push(new Chart(gprCtx, {
                type: 'bar',
                data: {
                    labels: rounds.map(r => `R${r}`),
                    datasets: [{ label: 'Goals', data: goalsPerRound, backgroundColor: '#059669', borderRadius: 4 }]
                },
                options: { ...BASE_CHART_OPTIONS, indexAxis: 'x', plugins: { legend: { display: false } } }
            }));
        }

        // Home vs Away
        const haCtx = document.getElementById('homeAwayChart');
        if (haCtx && !haCtx._chartInit && appState.allMatches.length > 0) {
            haCtx._chartInit = true;
            const filtered = getFilteredMatches();
            const homeW = filtered.filter(m => (parseInt(m.intHomeScore)||0) > (parseInt(m.intAwayScore)||0)).length;
            const draws = filtered.filter(m => (parseInt(m.intHomeScore)||0) === (parseInt(m.intAwayScore)||0)).length;
            const awayW = filtered.filter(m => (parseInt(m.intHomeScore)||0) < (parseInt(m.intAwayScore)||0)).length;
            appState.chartInstances.push(new Chart(haCtx, {
                type: 'doughnut',
                data: {
                    labels: [`Home Win (${homeW})`, `Draw (${draws})`, `Away Win (${awayW})`],
                    datasets: [{ data: [homeW, draws, awayW], backgroundColor: ['#059669','#d97706','#2563eb'] }]
                },
                options: {
                    responsive: true, maintainAspectRatio: false,
                    plugins: { legend: { position: 'bottom', labels: { font: { family: "'Inter',sans-serif", size: 11 }, color: '#8b949e' } }, tooltip: TOOLTIP_STYLE }
                }
            }));
        }

        // Home vs away performance (pts): top 10
        const hapCtx = document.getElementById('homeAwayPtsChart');
        if (hapCtx && !hapCtx._chartInit && (appState.standings || []).length > 0) {
            hapCtx._chartInit = true;
            const top10 = (appState.standings || []).slice(0, 10);
            appState.chartInstances.push(new Chart(hapCtx, {
                type: 'bar',
                data: {
                    labels: top10.map(t => t.name),
                    datasets: [
                        { label: 'Home Pts', data: top10.map(t => t.homeWins * 3 + t.homeDraws), backgroundColor: '#059669', borderRadius: 3 },
                        { label: 'Away Pts',  data: top10.map(t => t.awayWins * 3 + t.awayDraws), backgroundColor: '#2563eb', borderRadius: 3 },
                    ]
                },
                options: {
                    ...BASE_CHART_OPTIONS,
                    plugins: { legend: { labels: { font: { family: "'Inter',sans-serif", size: 11 }, color: '#8b949e' } }, tooltip: TOOLTIP_STYLE },
                }
            }));
        }

}




/* ============================================================================
 * SECTION 7: DATA LOADING AND UPDATES
 * ============================================================================ */

/**
 * Loads the JSON files generated by the Python scripts and renders the dashboard.
 * Shows a "no data" screen if the files do not exist yet.
 */
async function loadData() {
    const appDiv = document.getElementById('app');
    try {
        appDiv.innerHTML = renderLoading();

        const [brRes, mktRes] = await Promise.all([
            fetch(DATA_BRASILEIRAO),
            fetch(DATA_MARKET).catch(() => null),
        ]);

        if (brRes.status === 404 || !brRes.ok) {
            if (IS_STATIC) {
                // GitHub Pages: data must exist; show the empty state
                appState.season        = new Date().getFullYear();
                appState.allMatches    = [];
                appState.standings     = [];
                appState.selectedRound = 1;
                appState.lastUpdated   = null;
                window.MARKET_VALUES_DATA = { players: [], source: '', last_updated: '' };
                render();
                return;
            }
            // Local (Flask): start collection automatically
            appDiv.innerHTML = `<div class="loading-container">
                <div class="spinner"></div>
                <div class="loading-text">Fetching data for the first time&hellip;</div>
                <div style="font-size:12px;color:var(--text-muted);margin-top:8px">This may take around 30 seconds.</div>
            </div>`;
            startUpdate();
            return;
        }

        const brData = await brRes.json();
        window.BRASILEIRAO_DATA   = brData;
        window.MARKET_VALUES_DATA = (mktRes?.ok)
            ? await mktRes.json()
            : { players: [], source: '', last_updated: '' };

        if (window.MARKET_VALUES_DATA.eur_brl_rate) {
            EUR_TO_BRL = window.MARKET_VALUES_DATA.eur_brl_rate;
        }

        const matches = brData.matches || [];

        appState.season        = brData.season || new Date().getFullYear();
        appState.allMatches    = matches;
        appState.selectedRound = brData.latest_round || 1;
        appState.lastUpdated   = brData.last_updated
            ? new Date(brData.last_updated)
            : new Date();

        if (matches.length > 0) {
            const { standings, teamBadges } = calculateStandings(matches);
            standings.forEach(team => { team.badge = teamBadges[team.name]; });
            appState.standings = standings;
        } else {
            appState.standings = [];
        }

        render();
    } catch (error) {
        console.warn('Data not found, opening an empty dashboard:', error.message);
        appState.season        = new Date().getFullYear();
        appState.allMatches    = [];
        appState.standings     = [];
        appState.selectedRound = 1;
        appState.lastUpdated   = null;
        window.MARKET_VALUES_DATA = { players: [], source: '', last_updated: '' };
        render();
    }
}


/* ============================================================================
 * SECTION 8: UPDATE PIPELINE (SSE)
 * ============================================================================ */

/**
 * Opens the progress overlay and starts data collection via SSE
 * (GET /update endpoint on the Flask server).
 */
function startUpdate() {
    const overlay = document.getElementById('updateOverlay');
    overlay.classList.remove('hidden');

    const bar     = document.getElementById('progressBar');
    const pctEl   = document.getElementById('progressPct');
    const msgEl   = document.getElementById('updateMessage');
    const closeBtn = document.getElementById('updateCloseBtn');

    if (IS_STATIC) {
        // GitHub Pages: data updated via GitHub Actions
        bar.style.width      = '100%';
        bar.style.background = 'var(--accent-green)';
        pctEl.textContent    = '✓';
        msgEl.textContent    = 'Data is updated automatically via GitHub Actions (daily at 7am BRT).';
        closeBtn.classList.remove('hidden');
        return;
    }

    bar.style.width      = '0%';
    bar.style.background = 'var(--accent-green)';
    pctEl.textContent    = '0%';
    msgEl.textContent    = 'Starting...';
    closeBtn.classList.add('hidden');

    const evtSource = new EventSource('/update');

    evtSource.onmessage = (e) => {
        const data = JSON.parse(e.data);
        const pct  = Math.max(0, data.progress);

        msgEl.textContent    = data.message;
        bar.style.width      = `${pct}%`;
        pctEl.textContent    = `${pct}%`;

        if (data.step === 'done') {
            evtSource.close();
            setTimeout(() => {
                overlay.classList.add('hidden');
                loadData();
            }, 1500);
        }
        if (data.step === 'error') {
            evtSource.close();
            bar.style.background = 'var(--accent-red)';
            closeBtn.classList.remove('hidden');
        }
    };

    evtSource.onerror = () => {
        evtSource.close();
        msgEl.textContent    = 'Connection error. Is the server running on localhost:5000?';
        bar.style.background = 'var(--accent-red)';
        closeBtn.classList.remove('hidden');
    };
}

/* ============================================================================
 * INITIALISATION
 * ============================================================================ */

// Initialise theme (light/dark)
(function initTheme() {
    const saved = localStorage.getItem('theme') || 'dark';
    document.documentElement.setAttribute('data-theme', saved);
}());

// Inject the update overlay into the body
(function injectUpdateOverlay() {
    const overlay = document.createElement('div');
    overlay.id        = 'updateOverlay';
    overlay.className = 'update-overlay hidden';
    overlay.innerHTML = `
        <div class="update-modal">
            <div class="update-title">\u23F3 Updating Data</div>
            <div class="update-message" id="updateMessage">Starting...</div>
            <div class="progress-bar-track">
                <div class="progress-bar" id="progressBar" style="width:0%"></div>
            </div>
            <div class="progress-pct" id="progressPct">0%</div>
            <button class="btn-close hidden" id="updateCloseBtn">Close</button>
        </div>
    `;
    document.body.appendChild(overlay);
    document.getElementById('updateCloseBtn').addEventListener('click', () => {
        overlay.classList.add('hidden');
    });
}());

loadData();
